name: retail_mobile
description: "Retail App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^1.0.0
  flutter_riverpod: ^2.6.0
  http:
  shared_preferences:
  image_picker:
  permission_handler: ^11.3.1
  razorpay_flutter: ^1.3.7
  fluttertoast: ^8.2.4
  equatable:
  cached_network_image: ^3.4.1
  skeletonizer:
  url_launcher:
  intl:
  flutter_native_splash:
  connectivity_plus: ^6.1.2
  dotted_border:
  hive:
  hive_flutter:
  awesome_notifications: ^0.9.3+1
  path_provider:
  font_awesome_flutter: ^10.8.0
  uuid: ^4.5.1
  lottie: ^3.2.0
  flutter_dotenv: ^5.2.1
  pin_code_fields:
  logger: ^2.5.0
  google_nav_bar: ^5.0.7
  mobile_scanner:
  firebase_core:
  firebase_messaging:
  omni_datetime_picker: ^2.0.6
  fl_chart:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator:
  build_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - .env
