class CommonTexts {
  static List<String> uomUnits = [
    "BAGS (BAG)",
    "BALE (BAL)",
    "BUNDLES (BDL)",
    "BULKERS (BLR)",
    "BILLIONS OF UNITS (BOU)",
    "BOX (BOX)",
    "BOTTLES (BTL)",
    "BUNCHES (BUN)",
    "CANS (CAN)",
    "CUBIC METER (CBM)",
    "CUBIC-CENTIMETER (CCM)",
    "CENTIMETER (CM)",
    "CARTONS (CTN)",
    "DOZEN (DOZ)",
    "DRUM (DRM)",
    "GREAT GROSS (GGR)",
    "GRAMS (GM)",
    "GROSS (GRS)",
    "GROSS YARDS (GYS)",
    "KILOGRAMS (KGS)",
    "KILOLITER (KLR)",
    "KILOMETER (KM)",
    "LITER (LTR)",
    "MILLILITRE (MLT)",
    "METERS (MT)",
    "NUMBERS (NOS)",
    "PACKS (PAC)",
    "PIECES (PCS)",
    "PAIRS (PRS)",
    "QUINTAL (QTL)",
    "ROLLS (ROL)",
    "SETS (SET)",
    "SQUARE FEET (SQF)",
    "SQUARE METERS (SQM)",
    "SQUARE YARDS (SQY)",
    "TABLETS (TBS)",
    "TEN GROSS (TGR)",
    "THOUSANDS (THD)",
    "TONNES (TON)",
    "TUBES (TUB)",
    "US GALLONS (USG)",
    "UNITS (UNT)",
    "YARDS (YDS)"
  ];

  static List<String> tamilNaduDistricts = [
    "Ariyalur",
    "Chengalpattu",
    "Chennai",
    "Coimbatore",
    "Cuddalore",
    "Dharmapuri",
    "Dindigul",
    "Erode",
    "Kallakurichi",
    "Kancheepuram",
    "Karur",
    "Krishnagiri",
    "Madurai",
    "Mayiladuthurai",
    "Nagapattinam",
    "Namakkal",
    "Nilgiris",
    "Perambalur",
    "Pudukkottai",
    "Ramanathapuram",
    "Ranipet",
    "Salem",
    "Sivagangai",
    "Tenkasi",
    "Thanjavur",
    "Theni",
    "Thoothukudi",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tirupattur",
    "Tiruppur",
    "Tiruvallur",
    "Tiruvannamalai",
    "Tiruvarur",
    "Vellore",
    "Viluppuram",
    "Virudhunagar"
  ];

  static List<String> roleOptions = [
    'Manager',
    'Accountant',
    'Operator',
    'Salesman',
  ];

  static List<String> allowManagement = [
    'Billing',
    'Shift',
    'Item Master',
    'Customer Master',
    'User Management',
    'Add Role',
    'Price / Stock',
    'Configuration',
    'Payment / Receipt',
  ];
}
